<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AnggotasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('anggotas')->delete();
        
        \DB::table('anggotas')->insert(array (
            0 => 
            array (
                'id' => '1',
                'nomor_anggota' => NULL,
                'nama' => 'Isep Lutpi Nur',
                'tanggal_lahir' => '2000-08-10',
                'jenis_kelamin' => 'laki-laki',
                'angkatan' => '2019',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203051',
                'village_id' => '3203051006',
                'alamat_lengkap' => 'Jl. Tipar, Rt 23/Rw 12 Dekat SD Negeri 1 Tipar',
                'bio' => 'Gajah mati meninggalkan gading, harimau mati meninggalkan belang, manusia mati meninggalkan nama. a',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'iseplutpinur20230218223312.jpg',
                'telepon' => '085798132505',
                'whatsapp' => '85798132505',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '1',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-18 22:33:12',
            ),
            1 => 
            array (
                'id' => '2',
                'nomor_anggota' => NULL,
                'nama' => 'HILAL MUHAMMAD FATURAHMAN',
                'tanggal_lahir' => '2000-04-25',
                'jenis_kelamin' => 'laki-laki',
                'angkatan' => '2018',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203010',
                'village_id' => '3203010001',
                'alamat_lengkap' => 'tes',
                'bio' => NULL,
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '16',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-12 02:12:19',
            ),
            2 => 
            array (
                'id' => '3',
                'nomor_anggota' => NULL,
                'nama' => 'NITA HALIMATUSSA’DIYAH',
                'tanggal_lahir' => '2002-06-15',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2020',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203071',
                'village_id' => '3203071007',
                'alamat_lengkap' => 'Jl. Ciburan Kp. Pogor Ds. Cibodas Kec. Cijati Kab. Cianjur',
                'bio' => 'Hai,
Gomawo',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'nita-hasa20220901014447.png',
                'telepon' => '085321186477',
                'whatsapp' => '85321186477',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '17',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-11 00:40:11',
            ),
            3 => 
            array (
                'id' => '4',
                'nomor_anggota' => NULL,
                'nama' => 'ABDUL MUHLIS',
                'tanggal_lahir' => '2001-03-24',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'abdul_muhlis20220901014656.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '19',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-11 00:40:11',
            ),
            4 => 
            array (
                'id' => '5',
                'nomor_anggota' => NULL,
                'nama' => 'ANDI TAUFIK PERMADI',
                'tanggal_lahir' => '1999-06-13',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '20',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-11 00:40:11',
            ),
            5 => 
            array (
                'id' => '6',
                'nomor_anggota' => NULL,
                'nama' => 'SUKIRMAN MAULANA',
                'tanggal_lahir' => '2000-01-30',
                'jenis_kelamin' => 'laki-laki',
                'angkatan' => '2020',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203020',
                'village_id' => '3203020009',
                'alamat_lengkap' => 'Kp. Ciakar RT.01 RW.05',
                'bio' => 'Manusia setengah ...',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'ukir20220901014322.png',
                'telepon' => '085724300377',
                'whatsapp' => '85724300377',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '21',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-11 00:40:11',
            ),
            6 => 
            array (
                'id' => '7',
                'nomor_anggota' => NULL,
                'nama' => 'DEWI',
                'tanggal_lahir' => '2001-09-19',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2019',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => '2019dewi20220901012915.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '22',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-11 00:40:11',
            ),
            7 => 
            array (
                'id' => '8',
                'nomor_anggota' => NULL,
                'nama' => 'WIWIT AWALIYAH',
                'tanggal_lahir' => '2000-11-02',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'wiwit_awaliyah20220901013532.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '23',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-11 00:40:11',
            ),
            8 => 
            array (
                'id' => '9',
                'nomor_anggota' => NULL,
                'nama' => 'SAEPUL ROHMAN',
                'tanggal_lahir' => '2000-05-10',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'saepul-rohman20220901020522.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '24',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-11 00:40:11',
            ),
            9 => 
            array (
                'id' => '10',
                'nomor_anggota' => NULL,
                'nama' => 'HILMI FITRIANI FUAIADAH',
                'tanggal_lahir' => '2000-12-29',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'hilmiff20220901011255.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '26',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-11 00:40:11',
            ),
            10 => 
            array (
                'id' => '11',
                'nomor_anggota' => NULL,
                'nama' => 'SAMSUL MA\'ARIP',
                'tanggal_lahir' => '2001-01-15',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'samsul_m20220901012257.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '27',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-11 00:40:11',
            ),
            11 => 
            array (
                'id' => '12',
                'nomor_anggota' => NULL,
                'nama' => 'MUHAMAD RAIHAN RAHMAN',
                'tanggal_lahir' => '2000-09-23',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '28',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-11 00:40:11',
            ),
            12 => 
            array (
                'id' => '13',
                'nomor_anggota' => NULL,
                'nama' => 'AKBAR MUHAMAD ASHONI',
                'tanggal_lahir' => '2002-03-01',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '29',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-11 00:40:11',
            ),
            13 => 
            array (
                'id' => '14',
                'nomor_anggota' => NULL,
                'nama' => 'WAHID NURSIDIK',
                'tanggal_lahir' => '2000-06-04',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'wahid_nursidik20220901022514.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '30',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-11 00:40:11',
            ),
            14 => 
            array (
                'id' => '15',
                'nomor_anggota' => NULL,
                'nama' => 'M FAISAL L',
                'tanggal_lahir' => '2001-06-13',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '31',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-11 00:40:11',
            ),
            15 => 
            array (
                'id' => '16',
                'nomor_anggota' => NULL,
                'nama' => 'SALAFIA AL ZAHRA FAUZIA',
                'tanggal_lahir' => '2001-06-07',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'salafiaazf20220901011223.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '32',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-11 00:40:11',
            ),
            16 => 
            array (
                'id' => '17',
                'nomor_anggota' => NULL,
                'nama' => 'YUSI YUSFITA',
                'tanggal_lahir' => '2001-04-15',
                'jenis_kelamin' => NULL,
                'angkatan' => '2019',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203050',
                'village_id' => '3203050003',
                'alamat_lengkap' => 'Kp. Hamerang Desa Hamerang Rt/Rw 01/01',
                'bio' => NULL,
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'yusi_yusfita20220901022340.png',
                'telepon' => '085723773793',
                'whatsapp' => '85723773793',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '33',
                'created_at' => '2023-02-11 00:40:11',
                'updated_at' => '2023-02-11 00:40:11',
            ),
            17 => 
            array (
                'id' => '18',
                'nomor_anggota' => NULL,
                'nama' => 'CUCU MARYAM NURPADILAH',
                'tanggal_lahir' => '2000-10-10',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203011',
                'village_id' => '3203011011',
                'alamat_lengkap' => 'Kp. Simpangsari RT 02/03 Ds. Mandalawangi Kec. Leles Kab. Cianjur',
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'cucu_maryam_nurfadilah20220901022428.png',
                'telepon' => '085724504674',
                'whatsapp' => '85724504674',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '34',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            18 => 
            array (
                'id' => '19',
                'nomor_anggota' => NULL,
                'nama' => 'RIFKI ALFAIZAR',
                'tanggal_lahir' => '2000-03-01',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'rifki_alfaizar20220901020211.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '35',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            19 => 
            array (
                'id' => '20',
                'nomor_anggota' => NULL,
                'nama' => 'M. RIDWAN ABDUL AZIZ',
                'tanggal_lahir' => '2000-03-01',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '36',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            20 => 
            array (
                'id' => '21',
                'nomor_anggota' => NULL,
                'nama' => 'NOVIANTI',
                'tanggal_lahir' => '2000-02-25',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '37',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            21 => 
            array (
                'id' => '22',
                'nomor_anggota' => NULL,
                'nama' => 'AYU PRATIWI ISMAN',
                'tanggal_lahir' => '2000-01-05',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '38',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            22 => 
            array (
                'id' => '23',
                'nomor_anggota' => NULL,
                'nama' => 'AI RAHMA ALIA',
                'tanggal_lahir' => '2000-01-01',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '39',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            23 => 
            array (
                'id' => '24',
                'nomor_anggota' => NULL,
                'nama' => 'ANDI AULIANSYAH',
                'tanggal_lahir' => '1998-09-27',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '40',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            24 => 
            array (
                'id' => '25',
                'nomor_anggota' => NULL,
                'nama' => 'KHORIDARUL ANISA',
                'tanggal_lahir' => '2002-01-29',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '41',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            25 => 
            array (
                'id' => '26',
                'nomor_anggota' => NULL,
                'nama' => 'ALWAN A F',
                'tanggal_lahir' => '2001-04-18',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '42',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            26 => 
            array (
                'id' => '27',
                'nomor_anggota' => NULL,
                'nama' => 'MUHAMMAD CAHYADI',
                'tanggal_lahir' => '1999-08-16',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203051',
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'muhammad_cahyadi20220901015206.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '43',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            27 => 
            array (
                'id' => '28',
                'nomor_anggota' => NULL,
                'nama' => 'AHMAD KAMIL',
                'tanggal_lahir' => '1999-02-16',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '44',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            28 => 
            array (
                'id' => '29',
                'nomor_anggota' => NULL,
                'nama' => 'SRI AYUNI WAHYUDIN',
                'tanggal_lahir' => '2002-03-20',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'sri_ayuni_wahyudin20220901021343.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '45',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-03-08 13:27:45',
            ),
            29 => 
            array (
                'id' => '30',
                'nomor_anggota' => NULL,
                'nama' => 'ENCEP ABDUL HAKIM',
                'tanggal_lahir' => '2001-08-27',
                'jenis_kelamin' => 'laki-laki',
                'angkatan' => '2020',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203050',
                'village_id' => '3203050005',
                'alamat_lengkap' => 'Jl.cilubang 
Kp.cilubang rt/rw 019/004',
                'bio' => 'Hidup dengan kebebasan',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'ncepkazama2720220901010244.png',
                'telepon' => '085524947588',
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '46',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            30 => 
            array (
                'id' => '31',
                'nomor_anggota' => NULL,
                'nama' => 'LINDAWATI RUSLIHA',
                'tanggal_lahir' => '1999-10-24',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '47',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            31 => 
            array (
                'id' => '32',
                'nomor_anggota' => NULL,
                'nama' => 'LINA HERLINA',
                'tanggal_lahir' => '1999-12-14',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '49',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            32 => 
            array (
                'id' => '33',
                'nomor_anggota' => NULL,
                'nama' => 'AGUSTIANI SRI RAHAYU',
                'tanggal_lahir' => '2001-08-01',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2019',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203061',
                'village_id' => '3203061008',
                'alamat_lengkap' => 'Kp.Rawadewa RT 002 RW 002 patokan dekat mesjid',
                'bio' => 'Don\'t come if only to go',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => NULL,
                'telepon' => '085861225643',
                'whatsapp' => '85861225643',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '50',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            33 => 
            array (
                'id' => '34',
                'nomor_anggota' => NULL,
                'nama' => 'RURI C. HETIAWATI',
                'tanggal_lahir' => '2000-10-26',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'ruri_c_hetiawati20220901013242.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '51',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            34 => 
            array (
                'id' => '35',
                'nomor_anggota' => NULL,
                'nama' => 'RINRIN IRMAYANI',
                'tanggal_lahir' => '2000-10-30',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '52',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            35 => 
            array (
                'id' => '36',
                'nomor_anggota' => NULL,
                'nama' => 'AI DIAN HAERANI',
                'tanggal_lahir' => '2001-04-15',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '53',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            36 => 
            array (
                'id' => '37',
                'nomor_anggota' => NULL,
                'nama' => 'APRILIA UTAMI HERDI',
                'tanggal_lahir' => '2002-04-03',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'aprilia_utami_herdi20220901020307.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '54',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            37 => 
            array (
                'id' => '38',
                'nomor_anggota' => NULL,
                'nama' => 'SITI BASIROH',
                'tanggal_lahir' => '2000-07-08',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '55',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            38 => 
            array (
                'id' => '39',
                'nomor_anggota' => NULL,
                'nama' => 'NU’MAN BASIR',
                'tanggal_lahir' => '1999-09-08',
                'jenis_kelamin' => 'laki-laki',
                'angkatan' => '2019',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203060',
                'village_id' => '3203060004',
                'alamat_lengkap' => 'Kp. BOJONG SIRNA RT/RW 003/002',
                'bio' => 'Beragamalah sesuai dosisnya',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'nu-man-basir20220901011159.png',
                'telepon' => NULL,
                'whatsapp' => '085848724272',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '57',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            39 => 
            array (
                'id' => '40',
                'nomor_anggota' => NULL,
                'nama' => 'MAULANA YUSUF',
                'tanggal_lahir' => '2000-04-29',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'maulana_yusuf20220901020046.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '58',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            40 => 
            array (
                'id' => '41',
                'nomor_anggota' => NULL,
                'nama' => 'INDRA KURNIA',
                'tanggal_lahir' => '2010-10-10',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '59',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            41 => 
            array (
                'id' => '42',
                'nomor_anggota' => NULL,
                'nama' => 'EGI',
                'tanggal_lahir' => '2020-10-10',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '60',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            42 => 
            array (
                'id' => '43',
                'nomor_anggota' => NULL,
                'nama' => 'M RIDWANAN',
                'tanggal_lahir' => '2022-02-21',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '61',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            43 => 
            array (
                'id' => '44',
                'nomor_anggota' => NULL,
                'nama' => 'WITA DEWI LESTARI',
                'tanggal_lahir' => '2010-10-10',
                'jenis_kelamin' => NULL,
                'angkatan' => '2018',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '62',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            44 => 
            array (
                'id' => '45',
                'nomor_anggota' => NULL,
                'nama' => 'M SYAHRUL RAMADHAN',
                'tanggal_lahir' => '2000-10-10',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'm-syahrul-ramadhan20220901015115.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '63',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            45 => 
            array (
                'id' => '46',
                'nomor_anggota' => NULL,
                'nama' => 'ILHAM FAOZ',
                'tanggal_lahir' => '2010-10-10',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'ilham_faoz20220901021242.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '64',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            46 => 
            array (
                'id' => '47',
                'nomor_anggota' => NULL,
                'nama' => 'ADRIAN SYAMSYUL RAMLI',
                'tanggal_lahir' => '2020-10-10',
                'jenis_kelamin' => NULL,
                'angkatan' => '2019',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'adrian_syamsyul_ramli20220901023041.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '65',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            47 => 
            array (
                'id' => '48',
                'nomor_anggota' => NULL,
                'nama' => 'AGUNG SETIABUDI',
                'tanggal_lahir' => '2020-10-10',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '67',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            48 => 
            array (
                'id' => '49',
                'nomor_anggota' => NULL,
                'nama' => 'YUSUF MUGHNI',
                'tanggal_lahir' => '2022-01-05',
                'jenis_kelamin' => NULL,
                'angkatan' => '2019',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'yusuf_mugni20220901012214.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '68',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            49 => 
            array (
                'id' => '50',
                'nomor_anggota' => NULL,
                'nama' => 'SITI SUROH HOLISOH',
                'tanggal_lahir' => '2000-10-10',
                'jenis_kelamin' => NULL,
                'angkatan' => '2012',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'siti_suroh_holisoh20220901022805.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '69',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            50 => 
            array (
                'id' => '51',
                'nomor_anggota' => NULL,
                'nama' => 'SAEPUL FIKRI',
                'tanggal_lahir' => '2022-12-03',
                'jenis_kelamin' => NULL,
                'angkatan' => '2019',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '70',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            51 => 
            array (
                'id' => '52',
                'nomor_anggota' => NULL,
                'nama' => 'MUHAMMAD FIKI NUGRAHA',
                'tanggal_lahir' => '2020-10-10',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => NULL,
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '71',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            52 => 
            array (
                'id' => '53',
                'nomor_anggota' => NULL,
                'nama' => 'SRI HASTUTI',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'sri_hastuti20220901012636.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '72',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            53 => 
            array (
                'id' => '54',
                'nomor_anggota' => NULL,
                'nama' => 'DERIS KUSNAEDI',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => 'laki-laki',
                'angkatan' => '2021',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203071',
                'village_id' => '3203071006',
                'alamat_lengkap' => 'Jalan Ahmad Sobandi, Kp. Tegal Manggu RT 02/RW 03',
                'bio' => 'Tak akan selalu mudah, tapi tetaplah mencoba lakukan apa yang benar',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'deris_kusnaedi20220901012740.png',
                'telepon' => '085759568797',
                'whatsapp' => '85759568797',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '73',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            54 => 
            array (
                'id' => '55',
                'nomor_anggota' => NULL,
                'nama' => 'Feri Firmansyah',
                'tanggal_lahir' => '2003-01-02',
                'jenis_kelamin' => 'laki-laki',
                'angkatan' => '2021',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203071',
                'village_id' => '3203071007',
                'alamat_lengkap' => 'Jalan Ahmad Sobandi Kecamatan Cijati Desa Cibodas Kp Burujul Rt2 Rw3/ Depan Kantor Kecamatan Cijati',
                'bio' => 'Ubahlah hidupmu dari hari ini. jangan pernah bertaruh pada masa depan, Kamu harus bertindak sekarang tanpa menunda-nunda kesempatan.',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'feri-firmansyah20220927195247.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '74',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            55 => 
            array (
                'id' => '56',
                'nomor_anggota' => NULL,
                'nama' => 'NISYARA SEPTIARANI SUKMA',
                'tanggal_lahir' => '2001-09-20',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2020',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203090',
                'village_id' => '3203090010',
                'alamat_lengkap' => 'Kp. Sindangreret Rt/rw. 04/07 Desa Sukamekar, Kecamatan Sukanagara, Kabupaten Cianjur, Provinsi Jawa Barat',
                'bio' => NULL,
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'nisyara20220901012515.png',
                'telepon' => '+6285759247975',
                'whatsapp' => '85759247975',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '75',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            56 => 
            array (
                'id' => '57',
                'nomor_anggota' => NULL,
                'nama' => 'SITI NURJAMILAH',
                'tanggal_lahir' => '2002-11-22',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2021',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203060',
                'village_id' => '3203060010',
                'alamat_lengkap' => 'Kp. Tegalmerak Desa. Pagermaneuh Kec. Tanggeung Kab. Cianjur RT 004/RW 004',
                'bio' => 'Agar sukses kemauanmu untuk berhasil harus lebih besar dari pada ketakutanmu untuk gagal.',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'jemi20220901010919.png',
                'telepon' => '085723844887',
                'whatsapp' => '85723844887',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '76',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            57 => 
            array (
                'id' => '58',
                'nomor_anggota' => NULL,
                'nama' => 'PUPUNG RUSTIKA',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'pupung_rustika20220901022556.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '77',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            58 => 
            array (
                'id' => '59',
                'nomor_anggota' => NULL,
                'nama' => 'HASBI ABDUL HUSAIN',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'hasbi_abdul_husain20220901022252.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '78',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            59 => 
            array (
                'id' => '60',
                'nomor_anggota' => NULL,
                'nama' => 'NUR HASAN',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'nur-hasan-20220901022838.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '79',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            60 => 
            array (
                'id' => '61',
                'nomor_anggota' => NULL,
                'nama' => 'ARSILA KHAIRUNNISA',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'arsila_khairunnisa20220901022924.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '80',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            61 => 
            array (
                'id' => '62',
                'nomor_anggota' => NULL,
                'nama' => 'Sofy Tri Alfiani',
                'tanggal_lahir' => '2002-05-09',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2020',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203060',
                'village_id' => '3203060004',
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'sofy20220901021549.png',
                'telepon' => '081572561094',
                'whatsapp' => '81572561094',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '81',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            62 => 
            array (
                'id' => '63',
                'nomor_anggota' => NULL,
                'nama' => 'Ragil JS Munster',
                'tanggal_lahir' => '2002-01-21',
                'jenis_kelamin' => 'laki-laki',
                'angkatan' => '2020',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203010',
                'village_id' => '3203010011',
                'alamat_lengkap' => NULL,
                'bio' => 'Yang baca I LOVE YOU ❤️',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'ragil_jsm20220901021834.png',
                'telepon' => '085156810593',
                'whatsapp' => '85156810593',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '82',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            63 => 
            array (
                'id' => '64',
                'nomor_anggota' => NULL,
                'nama' => 'MUHAMMAD IMAN NURJAMAN',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'm_iman_nurjaman20220901021936.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '83',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            64 => 
            array (
                'id' => '65',
                'nomor_anggota' => NULL,
                'nama' => 'Moh Indra Sukmara Esma',
                'tanggal_lahir' => '2002-10-29',
                'jenis_kelamin' => 'laki-laki',
                'angkatan' => '2021',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203060',
                'village_id' => '3203060003',
                'alamat_lengkap' => 'Kp. Pasirhuni RT/RW 02/02 Ds. Sukajaya Kec. Tanggeung',
                'bio' => 'Pemimpin Harus Memiliki Mimpi',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'moh-indra-sukmara-esma20220901021446.png',
                'telepon' => '085624931964',
                'whatsapp' => '85624931964',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '84',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            65 => 
            array (
                'id' => '66',
                'nomor_anggota' => NULL,
                'nama' => 'MUHAMMAD RAIHAN RAHMAN',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => 'laki-laki',
                'angkatan' => '2020',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203010',
                'village_id' => '3203010001',
                'alamat_lengkap' => NULL,
                'bio' => 'In my mind i do the best',
                'profesi' => NULL,
                'foto' => 'm_raihan_rahman20220901021647.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '85',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            66 => 
            array (
                'id' => '67',
                'nomor_anggota' => NULL,
                'nama' => 'IMAT ROHIMAT',
                'tanggal_lahir' => '2003-12-07',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2021',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203060',
                'village_id' => '3203060002',
                'alamat_lengkap' => 'Kp.Lembur Sawah Rt.02/06',
                'bio' => NULL,
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'imatrohimah20220901013625.png',
                'telepon' => '085714952976',
                'whatsapp' => '85714952976',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '86',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            67 => 
            array (
                'id' => '68',
                'nomor_anggota' => NULL,
                'nama' => 'Alvirda Damayanti Anwari',
                'tanggal_lahir' => '2001-05-02',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2019',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203080',
                'village_id' => '3203080005',
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'alvirdada20220901013709.png',
                'telepon' => '085861610741',
                'whatsapp' => '85861610741',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '87',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            68 => 
            array (
                'id' => '69',
                'nomor_anggota' => NULL,
                'nama' => 'SILVIA ANGGRAENI',
                'tanggal_lahir' => '2003-08-10',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2021',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203051',
                'village_id' => '3203051004',
                'alamat_lengkap' => 'Jln.raya Simpang-Koleberes Blok D, RT/RW 02/09. Desa Cikadu. Kecamatan Cikadu',
                'bio' => 'Saya adalah seseorang yang suka berorganisasi. Organisasi internal maupun eksternal. Saya rajin dan tekun dalam menjalankan suatu tugas atau misi.',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'silviaanggrnii20220901013330.png',
                'telepon' => '+62 856-9337-2448',
                'whatsapp' => '082315805012',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '89',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            69 => 
            array (
                'id' => '70',
                'nomor_anggota' => NULL,
                'nama' => 'AI YETI KOKOM KOMALASARI',
                'tanggal_lahir' => '2003-03-21',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2021',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203051',
                'village_id' => '3203051004',
                'alamat_lengkap' => 'Kp.Koleberes Blok D Rt 04 Rw 09 Desa Cikadu Kecamatan Cikadu Kabupaten Cianjur',
                'bio' => NULL,
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'ai_yeti20220901013845.png',
                'telepon' => '085719252001',
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '90',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            70 => 
            array (
                'id' => '71',
                'nomor_anggota' => NULL,
                'nama' => 'SIPA PUSPITA SARI',
                'tanggal_lahir' => '2001-02-26',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2020',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203060',
                'village_id' => '3203060004',
                'alamat_lengkap' => 'Kp. Layung sari RT/RW 001/005 Desa. Tanggeung Kec. Tanggeung Kab. Cianjur',
                'bio' => NULL,
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'sipa_puspitasari20220901013912.png',
                'telepon' => '085861183799',
                'whatsapp' => '85861183799',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '91',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            71 => 
            array (
                'id' => '72',
                'nomor_anggota' => NULL,
                'nama' => 'ADE MUNAWAR',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'ade-munawar20220901015026.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '92',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            72 => 
            array (
                'id' => '73',
                'nomor_anggota' => NULL,
                'nama' => 'ABDUL AZIZ',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => 'laki-laki',
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'abdul-aziz-20220901015714.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '93',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            73 => 
            array (
                'id' => '74',
                'nomor_anggota' => NULL,
                'nama' => 'GUSAERI',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => 'laki-laki',
                'angkatan' => '2020',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203060',
                'village_id' => '3203060009',
                'alamat_lengkap' => NULL,
                'bio' => 'B aja.',
                'profesi' => 'kuli',
                'foto' => 'gusaeri-20220901015559.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '94',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            74 => 
            array (
                'id' => '75',
                'nomor_anggota' => NULL,
                'nama' => 'M. FAISHAL',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'm_faishal20220901015808.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '95',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            75 => 
            array (
                'id' => '76',
                'nomor_anggota' => NULL,
                'nama' => 'NASRIATUL HAMIDAH',
                'tanggal_lahir' => '2001-08-12',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2020',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203060',
                'village_id' => '3203060008',
                'alamat_lengkap' => 'Kp.Cipetir RT/RW 003/001',
                'bio' => 'free',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'nasiratul_hamidah20220901015851.png',
                'telepon' => '085220925934',
                'whatsapp' => '85220925934',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '96',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            76 => 
            array (
                'id' => '77',
                'nomor_anggota' => NULL,
                'nama' => 'NENG NURHASANAH',
                'tanggal_lahir' => '2001-05-15',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2020',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203100',
                'village_id' => '3203100003',
                'alamat_lengkap' => 'Kp Sukalaksana 04/03',
                'bio' => NULL,
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'nengnurhasanah20220901015639.png',
                'telepon' => '085861444715',
                'whatsapp' => '85861444715',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '97',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            77 => 
            array (
                'id' => '78',
                'nomor_anggota' => NULL,
                'nama' => 'SOLEHUDIN',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'solehudin20220901015934.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '98',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            78 => 
            array (
                'id' => '79',
                'nomor_anggota' => NULL,
                'nama' => 'AHMAD DIMYATI RIDWAN',
                'tanggal_lahir' => '2001-12-04',
                'jenis_kelamin' => 'laki-laki',
                'angkatan' => '2020',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203060',
                'village_id' => '3203060005',
                'alamat_lengkap' => 'Kp. Mekar Mulya, Ds. Kertajaya, RT/RW: 001/001, Kec. Tanggeung, Kab. Cianjur',
                'bio' => 'Penulis buku "Cinta adalah Luka"',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'ahmaddimyatiridwan1620220901014412.png',
                'telepon' => '081214648443',
                'whatsapp' => '81214648443',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '99',
                'created_at' => '2023-02-11 00:40:12',
                'updated_at' => '2023-02-11 00:40:12',
            ),
            79 => 
            array (
                'id' => '80',
                'nomor_anggota' => NULL,
                'nama' => 'ELISA PUTRI ANGGRAENI',
                'tanggal_lahir' => '2003-12-31',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2021',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => 'Kp. Batu Kunti Rt 001 Rw 005 Desa Karyabakti Kecamatan Cidaun Kabupaten Cianjur',
                'bio' => 'Haiii',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'elisaputrianggraeni20220901015442.png',
                'telepon' => '085798104331',
                'whatsapp' => '85798104331',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '100',
                'created_at' => '2023-02-11 00:40:13',
                'updated_at' => '2023-02-11 00:40:13',
            ),
            80 => 
            array (
                'id' => '81',
                'nomor_anggota' => NULL,
                'nama' => 'WIDI AYUNI MAULIDIA',
                'tanggal_lahir' => '2002-06-04',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2020',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => 'Kp. Pasir Malang RT 04 RW 04 desa sukamaju kecamatan Cibeber kab Cianjur Jawa Barat',
                'bio' => NULL,
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'widimailcom20220901014751.png',
                'telepon' => NULL,
                'whatsapp' => '85722768183',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '101',
                'created_at' => '2023-02-11 00:40:13',
                'updated_at' => '2023-02-11 00:40:13',
            ),
            81 => 
            array (
                'id' => '82',
                'nomor_anggota' => NULL,
                'nama' => 'RAMLAN HIDAYAT',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'ramlan_hidayat20220901014915.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '106',
                'created_at' => '2023-02-11 00:40:13',
                'updated_at' => '2023-02-11 00:40:13',
            ),
            82 => 
            array (
                'id' => '83',
                'nomor_anggota' => NULL,
                'nama' => 'AJENG KARTINI',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2020',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203051',
                'village_id' => '3203051006',
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'ajeng-kartini20220901020733.png',
                'telepon' => NULL,
                'whatsapp' => '85864221448',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '108',
                'created_at' => '2023-02-11 00:40:13',
                'updated_at' => '2023-02-11 00:40:13',
            ),
            83 => 
            array (
                'id' => '84',
                'nomor_anggota' => NULL,
                'nama' => 'M. ILHAM FAISAL',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'm_ilham_faisal20220901020630.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '109',
                'created_at' => '2023-02-11 00:40:13',
                'updated_at' => '2023-02-11 00:40:13',
            ),
            84 => 
            array (
                'id' => '85',
                'nomor_anggota' => NULL,
                'nama' => 'RISMAWANTI AWALIAH S',
                'tanggal_lahir' => '2003-07-10',
                'jenis_kelamin' => 'perempuan',
                'angkatan' => '2021',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203061',
                'village_id' => '3203061003',
                'alamat_lengkap' => 'KP GEGER 2 RT 020 RW 008 GIRIJAYA, PASIRKUDA, CIANJUR, JAWA BARAT',
                'bio' => 'Berpikir Positif dan Selalu Optimis ✨',
                'profesi' => 'Pelajar/Mahasiswa',
                'foto' => 'rismawanti-awaliah-s20220901020347.png',
                'telepon' => '085624388890',
                'whatsapp' => '85624388890',
                'status' => 'ANGGOTA BIASA',
                'user_id' => '110',
                'created_at' => '2023-02-11 00:40:13',
                'updated_at' => '2023-02-11 00:40:13',
            ),
            85 => 
            array (
                'id' => '86',
                'nomor_anggota' => NULL,
                'nama' => 'THIA RAMADHANI AMIN',
                'tanggal_lahir' => '2022-07-14',
                'jenis_kelamin' => NULL,
                'angkatan' => '2020',
                'province_id' => NULL,
                'regency_id' => NULL,
                'district_id' => NULL,
                'village_id' => NULL,
                'alamat_lengkap' => NULL,
                'bio' => NULL,
                'profesi' => NULL,
                'foto' => 'thia_ramadhani_amin20220901020445.png',
                'telepon' => NULL,
                'whatsapp' => NULL,
                'status' => 'ANGGOTA BIASA',
                'user_id' => '111',
                'created_at' => '2023-02-11 00:40:13',
                'updated_at' => '2023-02-11 00:40:13',
            ),
        ));
        
        
    }
}