<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class UserRolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // role
        $admin = Role::create(['name' => 'admin']);
        $member = Role::create(['name' => 'member']);

        // permission
        $admin_p = [
            ['name' => 'admin.dashboard', 'guard_name' => 'web'],
            ['name' => 'admin.user', 'guard_name' => 'web'],
            ['name' => 'admin.user.excel', 'guard_name' => 'web'],
            ['name' => 'admin.user.store', 'guard_name' => 'web'],
            ['name' => 'admin.user.delete', 'guard_name' => 'web'],
            ['name' => 'admin.user.update', 'guard_name' => 'web'],
            ['name' => 'admin.address.province', 'guard_name' => 'web'],
            ['name' => 'admin.address.province.select2', 'guard_name' => 'web'],
            ['name' => 'admin.address.province.store', 'guard_name' => 'web'],
            ['name' => 'admin.address.province.delete', 'guard_name' => 'web'],
            ['name' => 'admin.address.province.update', 'guard_name' => 'web'],
            ['name' => 'admin.address.regencie', 'guard_name' => 'web'],
            ['name' => 'admin.address.regencie.select2', 'guard_name' => 'web'],
            ['name' => 'admin.address.regencie.store', 'guard_name' => 'web'],
            ['name' => 'admin.address.regencie.delete', 'guard_name' => 'web'],
            ['name' => 'admin.address.regencie.update', 'guard_name' => 'web'],
            ['name' => 'admin.address.district', 'guard_name' => 'web'],
            ['name' => 'admin.address.district.select2', 'guard_name' => 'web'],
            ['name' => 'admin.address.district.store', 'guard_name' => 'web'],
            ['name' => 'admin.address.district.delete', 'guard_name' => 'web'],
            ['name' => 'admin.address.district.update', 'guard_name' => 'web'],
            ['name' => 'admin.address.village', 'guard_name' => 'web'],
            ['name' => 'admin.address.village.select2', 'guard_name' => 'web'],
            ['name' => 'admin.address.village.store', 'guard_name' => 'web'],
            ['name' => 'admin.address.village.delete', 'guard_name' => 'web'],
            ['name' => 'admin.address.village.update', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.data', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.data.add', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.data.edit', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.data.delete', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.data.insert', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.data.update', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.kategori', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.kategori.select2', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.kategori.insert', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.kategori.delete', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.kategori.update', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.tag', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.tag.select2', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.tag.insert', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.tag.delete', 'guard_name' => 'web'],
            ['name' => 'admin.artikel.tag.update', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.periode', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.periode.add', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.periode.edit', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.periode.active', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.periode.member', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.periode.detail', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.periode.delete', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.periode.insert', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.periode.update', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.jabatan.parent', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.jabatan.select2', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.jabatan.update', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.jabatan', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.jabatan.insert', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.jabatan.delete', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.jabatan.member.select2', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.jabatan.member', 'guard_name' => 'web'],
            ['name' => 'admin.pengurus.jabatan.member.update', 'guard_name' => 'web'],
            ['name' => 'admin.galeri', 'guard_name' => 'web'],
            ['name' => 'admin.galeri.select2', 'guard_name' => 'web'],
            ['name' => 'admin.galeri.insert', 'guard_name' => 'web'],
            ['name' => 'admin.galeri.delete', 'guard_name' => 'web'],
            ['name' => 'admin.galeri.update', 'guard_name' => 'web'],
            ['name' => 'admin.social_media', 'guard_name' => 'web'],
            ['name' => 'admin.social_media.insert', 'guard_name' => 'web'],
            ['name' => 'admin.social_media.delete', 'guard_name' => 'web'],
            ['name' => 'admin.social_media.update', 'guard_name' => 'web'],
            ['name' => 'admin.contact', 'guard_name' => 'web'],
            ['name' => 'admin.contact.insert', 'guard_name' => 'web'],
            ['name' => 'admin.contact.delete', 'guard_name' => 'web'],
            ['name' => 'admin.contact.update', 'guard_name' => 'web'],
            ['name' => 'admin.footer_instagram', 'guard_name' => 'web'],
            ['name' => 'admin.footer_instagram.insert', 'guard_name' => 'web'],
            ['name' => 'admin.footer_instagram.delete', 'guard_name' => 'web'],
            ['name' => 'admin.footer_instagram.update', 'guard_name' => 'web'],
            ['name' => 'admin.profile.pendidikan_jenis', 'guard_name' => 'web'],
            ['name' => 'admin.profile.pendidikan_jenis.insert', 'guard_name' => 'web'],
            ['name' => 'admin.profile.pendidikan_jenis.delete', 'guard_name' => 'web'],
            ['name' => 'admin.profile.pendidikan_jenis.update', 'guard_name' => 'web'],
            ['name' => 'admin.profile.kontak_tipe', 'guard_name' => 'web'],
            ['name' => 'admin.profile.kontak_tipe.insert', 'guard_name' => 'web'],
            ['name' => 'admin.profile.kontak_tipe.delete', 'guard_name' => 'web'],
            ['name' => 'admin.profile.kontak_tipe.update', 'guard_name' => 'web'],
            ['name' => 'admin.username_validation', 'guard_name' => 'web'],
            ['name' => 'admin.username_validation.select2', 'guard_name' => 'web'],
            ['name' => 'admin.username_validation.save', 'guard_name' => 'web'],
            ['name' => 'admin.pendaftaran', 'guard_name' => 'web'],
            ['name' => 'admin.pendaftaran.get_one', 'guard_name' => 'web'],
            ['name' => 'admin.pendaftaran.insert', 'guard_name' => 'web'],
            ['name' => 'admin.pendaftaran.delete', 'guard_name' => 'web'],
            ['name' => 'admin.pendaftaran.update', 'guard_name' => 'web'],
            ['name' => 'admin.pendaftaran.sensus', 'guard_name' => 'web'],
            ['name' => 'admin.pendaftaran.sensus.excel', 'guard_name' => 'web'],
            ['name' => 'admin.pendaftaran.sensus.status', 'guard_name' => 'web'],
            ['name' => 'admin.user_access.permission', 'guard_name' => 'web'],
            ['name' => 'admin.user_access.permission.select2', 'guard_name' => 'web'],
            ['name' => 'admin.user_access.permission.store', 'guard_name' => 'web'],
            ['name' => 'admin.user_access.permission.delete', 'guard_name' => 'web'],
            ['name' => 'admin.user_access.permission.update', 'guard_name' => 'web'],
            ['name' => 'admin.user_access.role', 'guard_name' => 'web'],
            ['name' => 'admin.user_access.role.create', 'guard_name' => 'web'],
            ['name' => 'admin.user_access.role.edit', 'guard_name' => 'web'],
            ['name' => 'admin.user_access.role.select2', 'guard_name' => 'web'],
            ['name' => 'admin.user_access.role.store', 'guard_name' => 'web'],
            ['name' => 'admin.user_access.role.update', 'guard_name' => 'web'],
            ['name' => 'admin.user_access.role.delete', 'guard_name' => 'web'],
        ];

        $member_p = [
            ['name' => 'member.dashboard', 'guard_name' => 'web'],
            ['name' => 'member.profile', 'guard_name' => 'web'],
            ['name' => 'member.profile.save_basic', 'guard_name' => 'web'],
            ['name' => 'member.profile.save_address', 'guard_name' => 'web'],
            ['name' => 'member.profile.save_detail', 'guard_name' => 'web'],
            ['name' => 'member.profile.kontak', 'guard_name' => 'web'],
            ['name' => 'member.profile.kontak_insert', 'guard_name' => 'web'],
            ['name' => 'member.profile.kontak_update', 'guard_name' => 'web'],
            ['name' => 'member.profile.kontak_delete', 'guard_name' => 'web'],
            ['name' => 'member.profile.hobby_select2', 'guard_name' => 'web'],
            ['name' => 'member.profile.hobby_save', 'guard_name' => 'web'],
            ['name' => 'member.profile.profesi_select2', 'guard_name' => 'web'],
            ['name' => 'member.profile.pendidikan', 'guard_name' => 'web'],
            ['name' => 'member.profile.pendidikan_select2', 'guard_name' => 'web'],
            ['name' => 'member.profile.pendidikan_insert', 'guard_name' => 'web'],
            ['name' => 'member.profile.pendidikan_update', 'guard_name' => 'web'],
            ['name' => 'member.profile.pendidikan_delete', 'guard_name' => 'web'],
            ['name' => 'member.profile.pengalaman_organisasi', 'guard_name' => 'web'],
            ['name' => 'member.profile.pengalaman_organisasi_select2', 'guard_name' => 'web'],
            ['name' => 'member.profile.pengalaman_organisasi_insert', 'guard_name' => 'web'],
            ['name' => 'member.profile.pengalaman_organisasi_update', 'guard_name' => 'web'],
            ['name' => 'member.profile.pengalaman_organisasi_delete', 'guard_name' => 'web'],
            ['name' => 'member.profile.pengalaman_lain', 'guard_name' => 'web'],
            ['name' => 'member.profile.pengalaman_lain_insert', 'guard_name' => 'web'],
            ['name' => 'member.profile.pengalaman_lain_update', 'guard_name' => 'web'],
            ['name' => 'member.profile.pengalaman_lain_delete', 'guard_name' => 'web'],
            ['name' => 'member.password', 'guard_name' => 'web'],
            ['name' => 'member.password.save', 'guard_name' => 'web'],
        ];

        foreach ($admin_p as $v) {
            $p = Permission::create($v);
            $admin->givePermissionTo($p);
        }

        foreach ($member_p as $v) {
            $p = Permission::create($v);
            $member->givePermissionTo($p);
            $admin->givePermissionTo($p);
        }
        $user_role = [
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 1],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 16],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 17],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 19],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 20],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 21],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 22],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 23],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 24],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 26],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 27],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 28],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 29],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 30],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 31],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 32],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 33],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 34],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 35],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 36],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 37],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 38],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 39],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 40],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 41],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 42],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 43],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 44],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 45],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 46],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 47],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 49],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 50],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 51],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 52],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 53],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 54],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 55],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 57],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 58],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 59],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 60],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 61],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 62],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 63],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 64],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 65],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 67],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 68],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 69],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 70],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 71],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 72],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 73],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 74],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 75],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 76],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 77],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 78],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 79],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 80],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 81],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 82],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 83],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 84],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 85],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 86],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 87],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 89],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 90],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 91],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 92],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 93],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 94],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 95],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 96],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 97],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 98],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 99],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 100],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 101],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 106],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 108],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 109],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 110],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 111],
        ];

        $tableNames = config('permission.table_names');
        DB::table($tableNames['model_has_roles'])->insert($user_role);
    }
}
