<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => '1',
                'name' => 'Isep Lutpi Nur',
                'email' => 'iseplutpinur7@gmail.com',
                'foto' => NULL,
                'username' => 'iseplutpinur',
                'email_verified_at' => NULL,
                'password' => '$2y$10$YdAlvluKvhUM9m2rq8xKc.Xba7afUVgCF7PZwvaq3C2sS7dg0xbRS',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => 'JqH3OWLTskjtzDRySl7kCnbPB6zTydtfK7Ih1h3HZwetPQl0UFF73QRNPSy7',
                'created_at' => NULL,
                'updated_at' => '2023-03-08 22:44:34',
            ),
            1 => 
            array (
                'id' => '16',
                'name' => 'HILAL MUHAMMAD FATURAHMAN',
                'email' => 'hilal@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-05-02 09:05:03',
            ),
            2 => 
            array (
                'id' => '17',
                'name' => 'NITA HALIMATUSSA’DIYAH',
                'email' => 'nita_halimatus_syadiah@mail.com',
                'foto' => NULL,
                'username' => 'nita-hasa',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:44:47',
            ),
            3 => 
            array (
                'id' => '19',
                'name' => 'ABDUL MUHLIS',
                'email' => 'abdul_muhlis@mail.com',
                'foto' => NULL,
                'username' => 'abdul_muhlis',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:46:56',
            ),
            4 => 
            array (
                'id' => '20',
                'name' => 'ANDI TAUFIK PERMADI',
                'email' => 'andi_taufik_permadi@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => '21',
                'name' => 'SUKIRMAN MAULANA',
                'email' => 'sukirman_maulana@mail.com',
                'foto' => NULL,
                'username' => 'ukir',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:43:22',
            ),
            6 => 
            array (
                'id' => '22',
                'name' => 'DEWI',
                'email' => 'dewi@mail.com',
                'foto' => NULL,
                'username' => '2019dewi',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:29:15',
            ),
            7 => 
            array (
                'id' => '23',
                'name' => 'WIWIT AWALIYAH',
                'email' => 'wiwit_awaliyah@mail.com',
                'foto' => NULL,
                'username' => 'wiwit_awaliyah',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:35:32',
            ),
            8 => 
            array (
                'id' => '24',
                'name' => 'SAEPUL ROHMAN',
                'email' => 'saepul_rohman@mail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:05:22',
            ),
            9 => 
            array (
                'id' => '26',
                'name' => 'HILMI FITRIANI FUAIADAH',
                'email' => 'hilmi_fitriani_fuaiadah@mail.com',
                'foto' => NULL,
                'username' => 'hilmiff',
                'email_verified_at' => NULL,
                'password' => '$2y$10$hsiSIKHHUg6I.B2h9IBATOzOgi8HOhzKnL3y7rEnmwR7LaLXOwBfG',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:12:55',
            ),
            10 => 
            array (
                'id' => '27',
                'name' => 'SAMSUL MA\'ARIP',
                'email' => 'samsul_maarip@mail.com',
                'foto' => NULL,
                'username' => 'samsul_m',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:22:57',
            ),
            11 => 
            array (
                'id' => '28',
                'name' => 'MUHAMAD RAIHAN RAHMAN',
                'email' => 'muhamad_raihan_rahman@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => '29',
                'name' => 'AKBAR MUHAMAD ASHONI',
                'email' => 'akbar_muhamad_ashoni@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => '30',
                'name' => 'WAHID NURSIDIK',
                'email' => 'wahid_nursidik@mail.com',
                'foto' => NULL,
                'username' => 'wahid_nursidik',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:25:14',
            ),
            14 => 
            array (
                'id' => '31',
                'name' => 'M FAISAL L',
                'email' => 'm_faisal_l@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => '32',
                'name' => 'SALAFIA AL ZAHRA FAUZIA',
                'email' => 'salafia_al_zahra_fauzia@mail.com',
                'foto' => NULL,
                'username' => 'salafiaazf',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:12:23',
            ),
            16 => 
            array (
                'id' => '33',
                'name' => 'YUSI YUSFITA',
                'email' => 'yusi_yusfita@mail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-10-01 14:54:52',
            ),
            17 => 
            array (
                'id' => '34',
                'name' => 'CUCU MARYAM NURPADILAH',
                'email' => 'cucu_maryam_nurfadilah@mail.com',
                'foto' => NULL,
                'username' => 'cucumaryamnurpadilah',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-29 18:27:48',
            ),
            18 => 
            array (
                'id' => '35',
                'name' => 'RIFKI ALFAIZAR',
                'email' => 'rifki_alfaizar@mail.com',
                'foto' => NULL,
                'username' => 'rifki_alfaizar',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:02:11',
            ),
            19 => 
            array (
                'id' => '36',
                'name' => 'M. RIDWAN ABDUL AZIZ',
                'email' => 'm._ridwan_abdul_aziz@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => '37',
                'name' => 'NOVIANTI',
                'email' => 'novianti@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => '38',
                'name' => 'AYU PRATIWI ISMAN',
                'email' => 'ayu_pratiwi_isman@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => '39',
                'name' => 'AI RAHMA ALIA',
                'email' => 'ai_rahma_alia@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => '40',
                'name' => 'ANDI AULIANSYAH',
                'email' => 'andi_auliansyah@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => '41',
                'name' => 'KHORIDARUL ANISA',
                'email' => 'khoridarul_anisa@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => '42',
                'name' => 'ALWAN A F',
                'email' => 'alwan_a_f@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => '43',
                'name' => 'MUHAMMAD CAHYADI',
                'email' => 'muhammad_cahyadi@mail.com',
                'foto' => NULL,
                'username' => 'muhammad_cahyadi',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:52:06',
            ),
            27 => 
            array (
                'id' => '44',
                'name' => 'AHMAD KAMIL',
                'email' => 'ahmad_kamil@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => '45',
                'name' => 'SRI AYUNI WAHYUDIN',
                'email' => 'sri_ayuni_wahyudin@mail.com',
                'foto' => NULL,
                'username' => 'sri_ayuni_wahyudin',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:13:43',
            ),
            29 => 
            array (
                'id' => '46',
                'name' => 'ENCEP ABDUL HAKIM',
                'email' => 'encep_abdul_hakim@mail.com',
                'foto' => NULL,
                'username' => 'ncepkazama27',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:02:44',
            ),
            30 => 
            array (
                'id' => '47',
                'name' => 'LINDAWATI RUSLIHA',
                'email' => 'lindawati_rusliha@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => '49',
                'name' => 'LINA HERLINA',
                'email' => 'lina_herlina@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => '50',
                'name' => 'AGUSTIANI SRI RAHAYU',
                'email' => 'agustiani_sri_rahayu@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-10-01 14:49:01',
            ),
            33 => 
            array (
                'id' => '51',
                'name' => 'RURI C. HETIAWATI',
                'email' => 'ruri_c_hetiawati@mail.com',
                'foto' => NULL,
                'username' => 'ruri_c_hetiawati',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:32:42',
            ),
            34 => 
            array (
                'id' => '52',
                'name' => 'RINRIN IRMAYANI',
                'email' => 'rinrin_irmayani@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => '53',
                'name' => 'AI DIAN HAERANI',
                'email' => 'ai_dian_haerani@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => '54',
                'name' => 'APRILIA UTAMI HERDI',
                'email' => 'aprilia_utami_herdi@mail.com',
                'foto' => NULL,
                'username' => 'aprilia_utami_herdi',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:03:07',
            ),
            37 => 
            array (
                'id' => '55',
                'name' => 'SITI BASIROH',
                'email' => 'siti_basiroh@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => '57',
                'name' => 'NU’MAN BASIR',
                'email' => 'numan_basir@mail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:11:59',
            ),
            39 => 
            array (
                'id' => '58',
                'name' => 'MAULANA YUSUF',
                'email' => 'maulana_yusuf@mail.com',
                'foto' => NULL,
                'username' => 'maulana_yusuf',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:00:46',
            ),
            40 => 
            array (
                'id' => '59',
                'name' => 'INDRA KURNIA',
                'email' => 'indra.kurnia@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-05-02 09:06:17',
            ),
            41 => 
            array (
                'id' => '60',
                'name' => 'EGI',
                'email' => 'egi@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => '61',
                'name' => 'M RIDWANAN',
                'email' => 'm.ridwanan@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => '62',
                'name' => 'WITA DEWI LESTARI',
                'email' => 'wita.dewi.lestari@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => '63',
                'name' => 'M SYAHRUL RAMADHAN',
                'email' => 'm_syahrul_ramdan@mail.com',
                'foto' => NULL,
                'username' => 'm_syahrul_ramadhan',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:51:21',
            ),
            45 => 
            array (
                'id' => '64',
                'name' => 'ILHAM FAOZ',
                'email' => 'ilham_faoz@mail.com',
                'foto' => NULL,
                'username' => 'ilham_faoz',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:12:42',
            ),
            46 => 
            array (
                'id' => '65',
                'name' => 'ADRIAN SYAMSYUL RAMLI',
                'email' => 'adrian_samsul_ramli@mail.com',
                'foto' => NULL,
                'username' => 'adrian_syamsyul_ramli',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:30:41',
            ),
            47 => 
            array (
                'id' => '67',
                'name' => 'AGUNG SETIABUDI',
                'email' => 'agung.setiabudi@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => '68',
                'name' => 'YUSUF MUGHNI',
                'email' => 'yusuf_mughni@mail.com',
                'foto' => NULL,
                'username' => 'yusuf_mugni',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:22:14',
            ),
            49 => 
            array (
                'id' => '69',
                'name' => 'SITI SUROH HOLISOH',
                'email' => 'siti_suroh_holisoh@mail.com',
                'foto' => NULL,
                'username' => 'siti_suroh_holisoh',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:28:05',
            ),
            50 => 
            array (
                'id' => '70',
                'name' => 'SAEPUL FIKRI',
                'email' => 'saepul.fikri@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => '71',
                'name' => 'MUHAMMAD FIKI NUGRAHA',
                'email' => 'm.fiki.nugraha@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => '72',
                'name' => 'SRI HASTUTI',
                'email' => 'sri_hastuti@mail.com',
                'foto' => NULL,
                'username' => 'sri_hastuti',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:26:36',
            ),
            53 => 
            array (
                'id' => '73',
                'name' => 'DERIS KUSNAEDI',
                'email' => 'deris_kusnaedi@mail.com',
                'foto' => NULL,
                'username' => 'deris_kusnaedi',
                'email_verified_at' => NULL,
                'password' => '$2y$10$9Vg8cKyrFo/Ccz05iXcuSejI0I.N3ec4tp4QbneJ5jGo1zt7D./h2',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:27:40',
            ),
            54 => 
            array (
                'id' => '74',
                'name' => 'Feri Firmansyah',
                'email' => 'feryfirmansyah280@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$RU9.XLMm.X3QijCDCBgjqOqjDOyCDBFeRXtQlDoDprqsSSdD5oitC',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-10-24 10:22:51',
            ),
            55 => 
            array (
                'id' => '75',
                'name' => 'NISYARA SEPTIARANI SUKMA',
                'email' => 'nisyara_septiarani_sukma@mail.com',
                'foto' => NULL,
                'username' => 'nisyara',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:25:16',
            ),
            56 => 
            array (
                'id' => '76',
                'name' => 'SITI NURJAMILAH',
                'email' => 'siti_nurjamilah@mail.com',
                'foto' => NULL,
                'username' => 'jemi',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:09:19',
            ),
            57 => 
            array (
                'id' => '77',
                'name' => 'PUPUNG RUSTIKA',
                'email' => 'pupung_rustika@mail.com',
                'foto' => NULL,
                'username' => 'pupung_rustika',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:25:56',
            ),
            58 => 
            array (
                'id' => '78',
                'name' => 'HASBI ABDUL HUSAIN',
                'email' => 'hasbi_abdul_husain@mail.com',
                'foto' => NULL,
                'username' => 'hasbi_abdul_husain',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:22:52',
            ),
            59 => 
            array (
                'id' => '79',
                'name' => 'NUR HASAN',
                'email' => 'nur_hasan@mail.com',
                'foto' => NULL,
                'username' => 'nurhasan',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:28:42',
            ),
            60 => 
            array (
                'id' => '80',
                'name' => 'ARSILA KHAIRUNNISA',
                'email' => 'arsila_khairunnisa@mail.com',
                'foto' => NULL,
                'username' => 'arsila_khairunnisa',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:29:24',
            ),
            61 => 
            array (
                'id' => '81',
                'name' => 'Sofy Tri Alfiani',
                'email' => 'trifyalfiani@gmail.com',
                'foto' => NULL,
                'username' => 'sofy',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:15:49',
            ),
            62 => 
            array (
                'id' => '82',
                'name' => 'Ragil JS Munster',
                'email' => 'ragilsaputra211998@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:18:37',
            ),
            63 => 
            array (
                'id' => '83',
                'name' => 'MUHAMMAD IMAN NURJAMAN',
                'email' => 'muhammad_iman_nurjaman@mail.com',
                'foto' => NULL,
                'username' => 'm_iman_nurjaman',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:19:36',
            ),
            64 => 
            array (
                'id' => '84',
                'name' => 'Moh Indra Sukmara Esma',
                'email' => 'Mohindra.Sukmaraesma29@gmail.com',
                'foto' => NULL,
                'username' => 'moh_indra_sukmara_esma',
                'email_verified_at' => NULL,
                'password' => '$2y$10$VDWYFdw4u68s9nvOp7G8A.HunvtPJWsi0eIWD6VFnn8lT7U5vEQzq',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:15:39',
            ),
            65 => 
            array (
                'id' => '85',
                'name' => 'MUHAMMAD RAIHAN RAHMAN',
                'email' => 'muhammad_raihan@mail.com',
                'foto' => NULL,
                'username' => 'm_raihan_rahman',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:16:47',
            ),
            66 => 
            array (
                'id' => '86',
                'name' => 'IMAT ROHIMAT',
                'email' => 'imat_rohimat@mail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-12-04 14:07:45',
            ),
            67 => 
            array (
                'id' => '87',
                'name' => 'Alvirda Damayanti Anwari',
                'email' => 'alfirda_damayanti@mail.com',
                'foto' => NULL,
                'username' => 'alvirdada',
                'email_verified_at' => NULL,
                'password' => '$2y$10$70Wi4nPsqKE6ihuqmyxmvOw.CMg825mlxqnKJJbXlSc/I6IukGEQe',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:37:09',
            ),
            68 => 
            array (
                'id' => '89',
                'name' => 'SILVIA ANGGRAENI',
                'email' => 'silvia_anggraeni@mail.com',
                'foto' => NULL,
                'username' => 'silviaanggrnii',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:35:23',
            ),
            69 => 
            array (
                'id' => '90',
                'name' => 'AI YETI KOKOM KOMALASARI',
                'email' => 'ai_yeti_kokom_komalasari@mail.com',
                'foto' => NULL,
                'username' => 'ai_yeti',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:38:45',
            ),
            70 => 
            array (
                'id' => '91',
                'name' => 'SIPA PUSPITA SARI',
                'email' => 'sipapuspita620@gmail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-07 11:43:35',
            ),
            71 => 
            array (
                'id' => '92',
                'name' => 'ADE MUNAWAR',
                'email' => 'ade_munawar@mail.com',
                'foto' => NULL,
                'username' => 'ade_munawar',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:50:36',
            ),
            72 => 
            array (
                'id' => '93',
                'name' => 'ABDUL AZIZ',
                'email' => 'abdul_aziz@mail.com',
                'foto' => NULL,
                'username' => 'abdul_aziz',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:57:53',
            ),
            73 => 
            array (
                'id' => '94',
                'name' => 'GUSAERI',
                'email' => 'gusaeri@mail.com',
                'foto' => NULL,
                'username' => 'gusaeri',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:56:04',
            ),
            74 => 
            array (
                'id' => '95',
                'name' => 'M. FAISHAL',
                'email' => 'm_faishal@mail.com',
                'foto' => NULL,
                'username' => 'm_faishal',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:58:08',
            ),
            75 => 
            array (
                'id' => '96',
                'name' => 'NASRIATUL HAMIDAH',
                'email' => 'nasriatulhamidah12@gmail.com',
                'foto' => NULL,
                'username' => 'nasiratul_hamidah',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DHRAQsNhXq6LEcSKHlr.2ejnw04g9NS39HT2gpsNa0TXWDv1ge37m',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:58:51',
            ),
            76 => 
            array (
                'id' => '97',
                'name' => 'NENG NURHASANAH',
                'email' => 'neng_nurhasanah@mail.com',
                'foto' => NULL,
                'username' => 'nengnurhasanah',
                'email_verified_at' => NULL,
                'password' => '$2y$10$GfZgE8CuTXHLJSc1btM86.ZIXupBUsQtDhv7tbwdkq4vacVXka1Jy',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:56:39',
            ),
            77 => 
            array (
                'id' => '98',
                'name' => 'SOLEHUDIN',
                'email' => 'solehudin@mail.com',
                'foto' => NULL,
                'username' => 'solehudin',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:59:34',
            ),
            78 => 
            array (
                'id' => '99',
                'name' => 'AHMAD DIMYATI RIDWAN',
                'email' => 'dimyatiridwanahmad@gmail.com',
                'foto' => NULL,
                'username' => 'ahmaddimyatiridwan16',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:44:12',
            ),
            79 => 
            array (
                'id' => '100',
                'name' => 'ELISA PUTRI ANGGRAENI',
                'email' => 'elisa_putri_anggraeni@mail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:54:44',
            ),
            80 => 
            array (
                'id' => '101',
                'name' => 'WIDI AYUNI MAULIDIA',
                'email' => 'widi@mail.com',
                'foto' => NULL,
                'username' => 'widimailcom',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:47:51',
            ),
            81 => 
            array (
                'id' => '106',
                'name' => 'RAMLAN HIDAYAT',
                'email' => 'ramlan_hidayat@mail.com',
                'foto' => NULL,
                'username' => 'ramlan_hidayat',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 01:49:15',
            ),
            82 => 
            array (
                'id' => '108',
                'name' => 'AJENG KARTINI',
                'email' => 'ajeng_kartini@mail.com',
                'foto' => NULL,
                'username' => 'ajeng_kartini_pcy',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:08:49',
            ),
            83 => 
            array (
                'id' => '109',
                'name' => 'M. ILHAM FAISAL',
                'email' => 'ilham_faisal_debo@mail.com',
                'foto' => NULL,
                'username' => 'm_ilham_faisal',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:06:30',
            ),
            84 => 
            array (
                'id' => '110',
                'name' => 'RISMAWANTI AWALIAH S',
                'email' => 'rismawati@mail.com',
                'foto' => NULL,
                'username' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 06:18:21',
            ),
            85 => 
            array (
                'id' => '111',
                'name' => 'THIA RAMADHANI AMIN',
                'email' => 'thia_ramadhani_amin@mail.com',
                'foto' => NULL,
                'username' => 'thia_ramadhani_amin',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DsI7ChQu4aIwEwc0CTlCnO66pBuIukicAIA/oIKwHD4AIGzIHmHZO',
                'active' => '1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2022-09-01 02:04:45',
            ),
        ));
        
        
    }
}